name: 'Setup Environment'
description: 'Setup Environment'

inputs:
  qt-version:
    description: 'Qt Version'
    required: false
    default: '5.15.2'

runs:
  using: "composite"
  steps:
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: ${{ inputs.qt-version }}
    - name: Install dependencies
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/0_setup_env.sh --dont_install_qt